// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhnjvupeojjprylrqtxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impobmp2dXBlb2pqcHJ5bHJxdHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjY2ODIsImV4cCI6MjA3Mzc0MjY4Mn0.uvnTLJzvU45hM3EN_6ewAW9RvDR-Q63W94dzN6-DsnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});